In [ ]:
import numpy as np
import pandas as pd

# 0.
stock 데이터와 ecocycle 데이터  읽어오기  
  
파일명 : quiz_1_stock.csv  
변수명: stock  
  
파일명: quiz_2_ecocycle_20200227.csv  
변수명: eco  
 encoding:'euc-kr'

In [ ]:
stock =

In [ ]:
eco =

# 1. 
다음 1월 수치(sales_1)와 2월 수치(sales_2)를 합쳐보자.

In [ ]:
np.random.seed(2020)
newspaper1 = ['경향신문신문', '국민일보신문', '동아일보신문', '문화일보신문', '서울신문신문', '세계일보신문','조선일보신문',  '중앙일보신문', '한겨레신문', '한국일보신문']
newspaper2 = ['경향신문신문', '국민일보신문', '동아일보신문', '문화일보신문', '서울신문신문', '세계일보신문']

sales1 = pd.Series(np.random.randint(1000, 9999, 10)*100, index=newspaper1)
sales2 = pd.Series(np.random.randint(1000, 9999, 6)*100, index=newspaper2)
print(sales1)
print(sales2)

경향신문신문    849100
국민일보신문    313900
동아일보신문    266100
문화일보신문    465500
서울신문신문    525300
세계일보신문    975200
조선일보신문    299400
중앙일보신문    689700
한겨레신문     162600
한국일보신문    187000
dtype: int64
경향신문신문    644500
국민일보신문    360800
동아일보신문    627600
문화일보신문    897400
서울신문신문    710000
세계일보신문    784900
dtype: int64

In [ ]:
'''
output:
경향신문신문    1493600.0
국민일보신문     674700.0
동아일보신문     893700.0
문화일보신문    1362900.0
서울신문신문    1235300.0
세계일보신문    1760100.0
조선일보신문          NaN
중앙일보신문          NaN
한겨레신문           NaN
한국일보신문          NaN
dtype: float64
'''

'\noutput:\n경향신문신문    1493600.0\n국민일보신문     674700.0\n동아일보신문     893700.0\n문화일보신문    1362900.0\n서울신문신문    1235300.0\n세계일보신문    1760100.0\n조선일보신문          NaN\n중앙일보신문          NaN\n한겨레신문           NaN\n한국일보신문          NaN\ndtype: float64\n'

# 2.
1월 대비 2월에 몇 % 상승했는지 구해보기

In [ ]:
'''
output:
경향신문신문    -24.096102
국민일보신문     14.941064
동아일보신문    135.851184
문화일보신문     92.781955
서울신문신문     35.160860
세계일보신문    -19.513946
조선일보신문           NaN
중앙일보신문           NaN
한겨레신문            NaN
한국일보신문           NaN
dtype: float64
'''

# 3.
sales1 데이터에 score 라고 정의된 사용자 함수를 적용해서 각 신문사의 등급을 확인해보자.

In [ ]:
def score(x):
    if x > 600000:
        s = 'A'
    elif x > 400000:
        s = 'B'
    else:
        s ='C'
    return s

In [ ]:
'''
output:
경향신문신문    A
국민일보신문    C
동아일보신문    C
문화일보신문    B
서울신문신문    B
세계일보신문    A
조선일보신문    C
중앙일보신문    A
한겨레신문     C
한국일보신문    C
dtype: object
'''

# 4.
stock 데이터의 '체결가','거래량(천주)', '거래대금(백만)' 컬럼에 대해 각각의 최대값, 최소값을 하나의 리스트로 반환.  

hint: apply 사용

In [ ]:
'''
체결가             [2267.25, 2118.88]
거래량(천주)       [836699.0, 488288.0]
거래대금(백만)    [8818232.0, 5444383.0]
dtype: object
'''

# 5 - 7 ecocycle data
출처: [공공데이터포털](https://www.data.go.kr/dataset/15028247/fileData.do)

친환경적 자원순환 정보

In [ ]:
eco.head(5)

# 5
describe를 통해 수치형 데이터와 그렇지 않은 데이터의 요약정보 보기

In [ ]:
'''
output:

공사시 생활폐기물 발생량	운영시 생활폐기물 발생량	생활폐기물 발생량	건설폐기물 처리현황_매립	건설폐기물 처리현황_소각	건설폐기물 처리현황_재활용	사업장배출시설계 폐기물의 처리 현황_매립	사업장배출시설계 폐기물의 처리 현황_소각	사업장 지정 폐기물의 처리 현황_매립	사업장 지정 폐기물의 처리 현황_재활용	생성일	수정일
count	2319.000000	1.404000e+03	1.402000e+03	1810.000000	2156.000000	2.349000e+03	1556.000000	1527.000000	1042.000000	1.098000e+03	0.0	0.0
mean	115.813083	5.913877e+04	4.115696e+05	-311.029486	-211.793799	1.696526e+04	-6.015688	265.820812	14375.689155	3.499256e+04	NaN	NaN
std	626.924019	1.453263e+06	1.439072e+06	21017.764974	19446.351262	2.907766e+05	24587.728606	5987.633731	50395.908218	1.295906e+05	NaN	NaN
min	0.000000	0.000000e+00	1.350000e+01	-888888.000000	-888888.000000	0.000000e+00	-888888.000000	0.000000	0.000000	0.000000e+00	NaN	NaN
25%	27.235000	5.611750e+01	4.760000e+04	0.300000	0.800000	4.223000e+02	11.950000	5.100000	303.575000	7.022750e+02	NaN	NaN
50%	51.000000	5.746500e+02	1.449500e+05	3.050000	4.050000	7.876000e+02	67.900000	31.800000	1414.700000	5.865850e+03	NaN	NaN
75%	99.815000	3.634975e+03	3.335500e+05	23.700000	15.550000	1.524800e+03	223.200000	107.800000	7839.675000	3.037940e+04	NaN	NaN
max	23437.800000	5.295500e+07	4.090220e+07	62400.000000	112700.000000	1.114560e+07	383500.000000	233400.000000	778071.500000	2.086771e+06	NaN	NaN
'''

In [ ]:
'''
output:
	  사업코드	시군구읍면동 명칭	사업장배출시설계 폐기물의 처리 현황_재활용	사업장배출시설계 폐기물의 처리 현황_해역배출	사업장 지정 폐기물의 처리 현황_소각	사업장 지정 폐기물의 처리 현황_기타	사용여부
count	3952	3951	1586	1342	1080	1014	3952
unique	2194	374	887	471	800	632	1
top	ND2011A002	사업지구	2055.6	0	0	0	Y
freq	21	728	8	91	11	27	3952
'''

# 6
eco 를 컬럼명을 기준, 오름차순 정렬을 하기

In [ ]:
'''
output:
	건설폐기물 처리현황_매립	건설폐기물 처리현황_소각	건설폐기물 처리현황_재활용	공사시 생활폐기물 발생량	사업장 지정 폐기물의 처리 현황_기타	사업장 지정 폐기물의 처리 현황_매립	사업장 지정 폐기물의 처리 현황_소각	사업장 지정 폐기물의 처리 현황_재활용	사업장배출시설계 폐기물의 처리 현황_매립	사업장배출시설계 폐기물의 처리 현황_소각	사업장배출시설계 폐기물의 처리 현황_재활용	사업장배출시설계 폐기물의 처리 현황_해역배출	사업코드	사용여부	생성일	생활폐기물 발생량	수정일	시군구읍면동 명칭	운영시 생활폐기물 발생량
0	NaN	NaN	NaN	56.25	NaN	NaN	NaN	NaN	NaN	0.5	13.7	NaN	JJ2005E006	Y	NaN	23200.0	NaN	진안군	0.00
1	NaN	NaN	NaN	56.25	NaN	NaN	NaN	NaN	0.1	0.6	14.9	6	JJ2005E006	Y	NaN	23000.0	NaN	임실군	0.00
2	NaN	NaN	NaN	19.20	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	WJ2005E011	Y	NaN	342800.0	NaN	원주시	0.00
... 과 같은 데이터 프레임이 되도록. 

'''

# 7
'생활폐기물 발생량' 이 가장 높은 순서대로 5개 rows를 출력

In [ ]:
'''
output:
 	사업코드 	시군구읍면동 명칭 	공사시 생활폐기물 발생량 	운영시 생활폐기물 발생량 	생활폐기물 발생량 	건설폐기물 처리현황_매립 	건설폐기물 처리현황_소각 	건설폐기물 처리현황_재활용 	사업장배출시설계 폐기물의 처리 현황_매립 	사업장배출시설계 폐기물의 처리 현황_소각 	사업장배출시설계 폐기물의 처리 현황_재활용 	사업장배출시설계 폐기물의 처리 현황_해역배출 	사업장 지정 폐기물의 처리 현황_매립 	사업장 지정 폐기물의 처리 현황_소각 	사업장 지정 폐기물의 처리 현황_재활용 	사업장 지정 폐기물의 처리 현황_기타 	생성일 	수정일 	사용여부
2711 	HG2008G003 	서울시 	NaN 	NaN 	40902200.0 	1843.7 	202.0 	30883.1 	162.7 	7.6 	430.5 	309.2 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	Y
2767 	ME2009G001 	서울특별시 	NaN 	NaN 	11525400.0 	1391.3 	199.5 	29079.8 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	Y
2421 	HG2008K001 	서울특별시 	NaN 	NaN 	11420000.0 	1843.7 	202.0 	30883.1 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	Y
250 	ME2007C016 	서울특별시 	324.0 	129.6 	11336800.0 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	NaN 	Y
3090 	HG2011G002 	서울특별시 	NaN 	NaN 	11336800.0 	1130.5 	113.7 	27363.2 	545.9 	130.5 	2656.9 	508 	32537.5 	11945.9 	31989.0 	7166.9 	NaN 	NaN 	Y
'''